source 'https://rubygems.org'

gem 'rspec', '~>3.0'
gem 'redis', '~>4.1'
gem 'sinatra', '~>2.0'
gem 'json', '~>2.3'
gem 'rack-test', '~>1.1.0'
gem 'sidekiq','~>6.0.7'
gem 'sidekiq-status'
gem 'activesupport'
gem 'pry'