apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: eatk8s-service     # Unique name of the resource
spec:
  type: LoadBalancer                 # Expose the Pods by opening a port on each Node and proxying it to the service.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: api
    port: 4567
    targetPort: 4567
  selector:
    app: eatk8s      